runtime: python27
api_version: 1
threadsafe: true

handlers:
- url: /stylesheets
  static_dir: stylesheets
- url: /javascript
  static_dir: javascript
- url: /templates
  static_dir: HTML
- url: /.*
  script: main.app

libraries:
- name: jinja2
  version: latest
